/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface AssetRegistryInterface extends utils.Interface {
  functions: {
    "assetCount()": FunctionFragment;
    "assets(uint256)": FunctionFragment;
    "getAsset(uint256)": FunctionFragment;
    "uploadAsset(string,string,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "assetCount" | "assets" | "getAsset" | "uploadAsset"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assetCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assets",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAsset",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadAsset",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "assetCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uploadAsset",
    data: BytesLike
  ): Result;

  events: {
    "AssetUploaded(uint256,address,string,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetUploaded"): EventFragment;
}

export interface AssetUploadedEventObject {
  id: BigNumber;
  creator: string;
  cid: string;
  name: string;
  price: BigNumber;
}
export type AssetUploadedEvent = TypedEvent<
  [BigNumber, string, string, string, BigNumber],
  AssetUploadedEventObject
>;

export type AssetUploadedEventFilter = TypedEventFilter<AssetUploadedEvent>;

export interface AssetRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AssetRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    assetCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    assets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, boolean] & {
        cid: string;
        creator: string;
        owner: string;
        price: BigNumber;
        name: string;
        exists: boolean;
      }
    >;

    getAsset(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, string, BigNumber, string]>;

    uploadAsset(
      cid: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  assetCount(overrides?: CallOverrides): Promise<BigNumber>;

  assets(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, boolean] & {
      cid: string;
      creator: string;
      owner: string;
      price: BigNumber;
      name: string;
      exists: boolean;
    }
  >;

  getAsset(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, string, string, BigNumber, string]>;

  uploadAsset(
    cid: PromiseOrValue<string>,
    name: PromiseOrValue<string>,
    price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    assetCount(overrides?: CallOverrides): Promise<BigNumber>;

    assets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, boolean] & {
        cid: string;
        creator: string;
        owner: string;
        price: BigNumber;
        name: string;
        exists: boolean;
      }
    >;

    getAsset(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, string, BigNumber, string]>;

    uploadAsset(
      cid: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "AssetUploaded(uint256,address,string,string,uint256)"(
      id?: null,
      creator?: null,
      cid?: null,
      name?: null,
      price?: null
    ): AssetUploadedEventFilter;
    AssetUploaded(
      id?: null,
      creator?: null,
      cid?: null,
      name?: null,
      price?: null
    ): AssetUploadedEventFilter;
  };

  estimateGas: {
    assetCount(overrides?: CallOverrides): Promise<BigNumber>;

    assets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAsset(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    uploadAsset(
      cid: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assetCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assets(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAsset(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uploadAsset(
      cid: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
