/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetRegistry } from "./AssetRegistry";
export * as factories from "./factories";
export { AssetRegistry__factory } from "./factories/AssetRegistry__factory";
